### ISSUE TITLE
Can’t find crate for ‘rustc_llvm’

### ISSUE THREAD

**Issue by spease** [murarth/rusti#98]
Happens when doing cargo test. The crate doesn’t appear to be available on crates.io anymore.

**Comment by murarth** [comment]
The crate `rustc_llvm` used by rusti is not and has never been on crates.io. It was a crate used in the internals of the Rust compiler and no longer exists. If you're getting an error about it not existing, it's because you're not using the correct version of rustc to compile rusti. See the README section [Building](https://github.com/murarth/rusti#building) on how to install and build using the correct version.

If you want to know why an old version of rustc is necessary to compile rusti, see issue #86.

**Comment by weaming** [comment]
Then this tool supports latest rustc features?

**Comment by murarth** [comment]
@weaming No. rusti is locked to rustc version nightly-2016-08-01. If you want a REPL that supports the latest Rust features, try the evcxr project: https://github.com/google/evcxr

**Comment by weaming** [comment]
@murarth yes, I found it finally, thanks still.
